# Site settings
author: Whitny E
title: My First Project
header-img: img/home-bg.png
email: wne4e2@gmail.com
copyright_name: Whitny E
description: > # this means to ignore newlines until "baseurl:"
  CLI 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  WhitnyNicole

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
